name = "hosting-greenstar-landingpage"
compatibility_date = "2026-06-03"
pages_build_output_dir = "dist"

main = "src/worker.ts"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "greenstar-leads"
database_id = "1c4e9e3c-7110-4523-9651-a721491df660"
